apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: openshift-gitops
spec:
  project: openshift-applications
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
    kustomize:
      path: .     
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-stefanb