apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: dev-stefanb
spec:
  template:
    spec:
      containers:
      - name: guestbook-ui
        ports:
        - containerPort: 8080